---

# Main tasks file for fail2ban role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::fail2ban'
    - 'role::fail2ban:init'

- name: Verif filtres bien en place
  template:
    src: "filter.j2"
    dest: "/etc/fail2ban/filter.d/{{ item.filter.name }}.conf"
  loop: "{{ fail2ban_services }}"
  notify: Restart Fail2Ban
  tags:
    - role::fail2ban
    - role::fail2ban:filter

- name: Verif jails bien en place
  template:
    src: "jail.j2"
    dest: "/etc/fail2ban/jail.d/{{ item.name }}.conf"
  loop: "{{ fail2ban_services }}"
  notify: Restart Fail2Ban
  tags:
    - role::fail2ban
    - role::fail2ban:jail

- name: Verif actions bien en place
  template:
    src: "action.j2"
    dest: "/etc/fail2ban/action.d/{{ item.action.name }}.conf"
  loop: "{{ fail2ban_services }}"
  notify: Restart Fail2Ban
  tags:
    - role::fail2ban
    - role::fail2ban:action
