---
- hosts: all
  become: true
  vars:
    fail2ban_services:
      - name: nextcloud
        logpath: /drbd/nuage/docker/stack/nuage/conf/fail2ban/nextcloud.log
        filter:
          name: nextcloud-filter
          definition:
            _groupsre: '(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)'
            failregex: '^{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:'
            datepattern: ',?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S(%%z)?"'
        action: iptables-docker-user
  roles:
    - fail2ban-config