---
- hosts: all
- become: true
  vars:
    fail2ban_services:
      - name: nextcloud
        enabled: true
        port: "80,443"
        logpath: /drbd/nuage/docker/stack/nuage/conf/fail2ban/nextcloud.log
        filter:
          name: nextcloud
          definition:
            _groupsre: '(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
            failregex: '^[%(_groupsre)s]\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:'
            datepattern: ',?\s*"time"\s*:\s*"%%Y-%%m-%%dT%%H:%%M:%%S(%%z)?'
        action:
          name: iptables-docker-user
          ban: "iptables -I DOCKER-USER -s <ip> -j DROP"
          unban: "iptables -D DOCKER-USER -s <ip> -j DROP"
        maxretry: 3
        findtime: 600
        bantime: 3600

      - name: dawantv
        enabled: true
        port: "80,443"
        logpath: /drbd/dawantv/docker/volumes/dawantv-logs/prod.log
        filter:
          name: dawantv
          definition:
            _groupsre: '(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
            failregex: '^[%(_groupsre)s]\s*app\.ERROR:\s*IP:\s*<HOST>%(_groupsre)s,?\s*Location:\s*http://www\.dawan\.tv/connexion\s*\[\]\s*\[\]\s*$'
            datepattern: '%%Y-%%m-%%dT%%H:%%M:%%S\.%%f%%z'
        action:
          name: iptables-docker-user
          ban: "iptables -I DOCKER-USER -s <ip> -j DROP"
          unban: "iptables -D DOCKER-USER -s <ip> -j DROP"
        maxretry: 3
        findtime: 600
        bantime: 3600
  roles:
    - fail2ban-config
